# Mean-Variance-Standard Deviation Calculator

In an NumPy matrix:
- axis 0 -> columns in the matrix
- axis 1 -> orws in the matrix

In [505]:
import numpy as np
from decimal import Decimal, getcontext

In [506]:
# Setting the precision
# getcontext().prec = 17

inputArr = [_ for _ in range(0, 9, 1)]

print(inputArr)

[0, 1, 2, 3, 4, 5, 6, 7, 8]


In [507]:
# Turning the array into NumPy array
npArr = np.array(inputArr)

# Reshaping the NumPy array into 3x3 matrix
# npArr = npArr.reshape((3, 3))

print(npArr)

print(npArr.dtype)

[0 1 2 3 4 5 6 7 8]
int64


In [508]:
# print(np.round(np.array([npArr[0][0], npArr[0][1], npArr[0][2]]).var(), 15))
loz = np.array([_ for _ in range(0, 9, 1)])
print(loz)

print(loz[[0, 1, 2]])

mean_rows = [loz[[0, 1, 2]].mean(), loz[[3, 4, 5]].mean(), loz[[6, 7, 8]].mean()]
mean_cols = [loz[[0, 3, 6]].mean(), loz[[1, 4, 7]].mean(), loz[[2, 5, 8]].mean()]

print(mean_rows)
print(mean_cols)

std_rows = [loz[[0, 1, 2]].std(), loz[[3, 4, 5]].std(), loz[[6, 7, 8]].std()]
std_cols = [loz[[0, 3, 6]].std(), loz[[1, 4, 7]].std(), loz[[2, 5, 8]].std()]

print("\n\n{}\n{}".format(std_rows, std_cols))

[0 1 2 3 4 5 6 7 8]
[0 1 2]
[1.0, 4.0, 7.0]
[3.0, 4.0, 5.0]


[0.816496580927726, 0.816496580927726, 0.816496580927726]
[2.449489742783178, 2.449489742783178, 2.449489742783178]


In [509]:
# print(npArr[:, 2].std())

# for ele in npArr[:, 2]:
#     print(ele)
    
# print(npArr[0, :])

In [510]:
# Casting the current data type from Int64 to Float32
npArr.astype("float64")

print(npArr)
print(npArr.dtype)

[0 1 2 3 4 5 6 7 8]
int64


In [511]:
class MatrixStatisticalCalculation:
    def __init__(self, npArr: np.array):
        # Reshaping the primary NumPy array into 3x3 matrix
        self._input = self.matrixTransformer(npArr)
        
    def matrixTransformer(self, npArr: np.array):
        if npArr.shape != (3, 3) and npArr.shape == (9, ):
            npArr = npArr.reshape(3, 3)
            return npArr
        
        elif npArr.shape == (3, 3):
            return npArr

        else:
            raise ValueError("Input Numpy Array must contain 9 numbers!!!")
    
    def getStd(self) -> list:
        data = []
        
        # Vertical axis
        stdAtCols = [self._input[:, 0].std(), self._input[:, 1].std(), self._input[:, 2].std()]
        print("Std at cols: {}".format(stdAtCols))
        
        # Horizontal axis
        stdAtRows = [self._input[0, :].std(), self._input[1, :].std(), self._input[2, :].std()]
        print("Std at rows: {}".format(stdAtRows))
        
        # Standard Deviation of the entire matrix
        stdMatrix = self._input.std()
        print("Std at matrix: {}".format(stdMatrix))
        
        data.append(stdAtCols)
        data.append(stdAtRows)
        data.append(stdMatrix)
        
        return data
    
    def getMean(self) -> list:
        data = []
        
        # Vertical axis
        meanAtCols = [self._input[:, 0].mean(), self._input[:, 1].mean(), self._input[:, 2].mean()]
        
        # Horizontal axis
        meanAtRows = [self._input[0, :].mean(), self._input[1, :].mean(), self._input[2, :].mean()]
        
        # Mean of the entire matrix
        meanMatrix = self._input.mean()
        
        data.append(meanAtCols)
        data.append(meanAtRows)
        data.append(meanMatrix)
        
        return data

    def getVariance(self) -> list:
        data = []
        
        # Vertical axis
        # varianceAtCols = self._input.var(axis=0)
        varianceAtCols = [self._input[:, 0].var(), self._input[:, 1].var(), self._input[:, 2].var()]
        
        # Horizontal axis
        varianceAtRows = [self._input[0, :].var(), self._input[1, :].var(), self._input[2, :].var()]
        
        # Variance of the entire matrix
        varianceMatrix = self._input.var()
        
        data.append(varianceAtCols)
        data.append(varianceAtRows)
        data.append(varianceMatrix)
        
        return data
    
    def getMin(self) -> list:
        data = []
        
        # Vertical axis
        # minAtCols = self._input.min(axis=0)
        minAtCols = [self._input[:, 0].min(), self._input[:, 1].min(), self._input[:, 2].min()]
        
        
        # Horizontal axis
        # minAtRows = self._input.min(axis=1)
        minAtRows = [self._input[0, :].min(), self._input[1, :].min(), self._input[2, :].min()]
        
        # Minimum value of the entire matrix
        minMatrix = self._input.min()
        
        # print("minAtCols {} -> data type: {}".format(minAtCols, minAtCols.dtype))
        # print("minAtRows {} -> data type: {}".format(minAtRows, minAtRows.dtype))
        # print("minMatrix {} -> data type: {}".format(minMatrix, minMatrix.dtype))
        
        data.append(minAtCols)
        data.append(minAtRows)
        data.append(minMatrix)
        
        # print("data: {}".format(data))
        
        return data
    
    def getMax(self) -> list:
        data = []
        
        # Vertical axis
        maxAtCols = list(self._input.max(axis=0))
        
        # Horizontal axis
        maxAtRows = list(self._input.max(axis=1))
        
        # Maximum value of the entire matrix
        maxMatrix = self._input.max()
        
        data.append(maxAtCols)
        data.append(maxAtRows)
        data.append(maxMatrix)
        
        # print("maxAtCols {} -> data type: {}".format(maxAtCols, maxAtCols.dtype))
        # print("maxAtRows {} -> data type: {}".format(maxAtRows, maxAtRows.dtype))
        # print("maxMatrix {} -> data type: {}".format(maxMatrix, maxMatrix.dtype))
        
        return data
    
    def getSum(self) -> list:
        data = []
        
        # Vertical axis
        sumAtCols = list(self._input.sum(axis=0))
        
        # Horizontal axis
        sumAtRows = list(self._input.sum(axis=1))
        
        # Sum of the entire matrix
        sumMatrix = self._input.sum()
        
        
        data.append(sumAtCols)
        data.append(sumAtRows)
        data.append(sumMatrix)
        
        return data
    
    def getStatisticalInfor(self) -> dict:
        meanData = self.getMean()
        varianceData = self.getVariance()
        stdData = self.getStd()  
        minData = self.getMin()
        maxData = self.getMax()
        sumData = self.getSum()

        calculations = {
            "mean": meanData,
            "variance": varianceData,
            "standard deviation": stdData,
            "max": maxData,
            "min": minData,
            "sum": sumData
        }
        return calculations
    

In [512]:
# test = npArr.max(axis=0).astype("int32")
# casted_test = test.astype("int32")

# test1 = npArr.max(axis=1).astype("int32")

# test2 = npArr.max().astype("int32")

# print(test)
# print("\n\n{}".format(test1))
# print("\n\n{}".format(test2))

# print(casted_test)

In [513]:
calculation = MatrixStatisticalCalculation(npArr)

print(calculation.getStd())

print("\n\n")

test3 = calculation.getVariance()
print(test3)
print("{0:.15f}".format(test3[1][0]))



Std at cols: [2.449489742783178, 2.449489742783178, 2.449489742783178]
Std at rows: [0.816496580927726, 0.816496580927726, 0.816496580927726]
Std at matrix: 2.581988897471611
[[2.449489742783178, 2.449489742783178, 2.449489742783178], [0.816496580927726, 0.816496580927726, 0.816496580927726], 2.581988897471611]



[[6.0, 6.0, 6.0], [0.6666666666666666, 0.6666666666666666, 0.6666666666666666], 6.666666666666667]
0.666666666666667


In [514]:
std = npArr.std()
print(std)

mean = npArr.mean()
print(mean)

maxVal = npArr.max()
print(maxVal)

minVal = npArr.min()
print(minVal)

sumVal = npArr.sum()
print(sumVal)

varianceVal = npArr.var()
print(varianceVal)
 

2.581988897471611
4.0
8
0
36
6.666666666666667


In [515]:
# len = len(npArr)

# print(len)

# # for row in npArr:
# #     print(row)

print(npArr)

print("\n\n")

for row in npArr:
    print(row)


[0 1 2 3 4 5 6 7 8]



0
1
2
3
4
5
6
7
8


In [516]:
import json

meanData = calculation.getMean()
varianceData = calculation.getVariance()
stdData = calculation.getStd()
minData = calculation.getMin()
maxData = calculation.getMax()
sumData = calculation.getSum()

calculations = {
    "mean": meanData,
    "variance": varianceData,
    "standard deviation": stdData,
    "max": maxData,
    "min": minData,
    "sum": sumData
}

print(calculations)
print(type(calculations))

Std at cols: [2.449489742783178, 2.449489742783178, 2.449489742783178]
Std at rows: [0.816496580927726, 0.816496580927726, 0.816496580927726]
Std at matrix: 2.581988897471611
{'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0], 'variance': [[6.0, 6.0, 6.0], [0.6666666666666666, 0.6666666666666666, 0.6666666666666666], 6.666666666666667], 'standard deviation': [[2.449489742783178, 2.449489742783178, 2.449489742783178], [0.816496580927726, 0.816496580927726, 0.816496580927726], 2.581988897471611], 'max': [[6, 7, 8], [2, 5, 8], 8], 'min': [[0, 1, 2], [0, 3, 6], 0], 'sum': [[9, 12, 15], [3, 12, 21], 36]}
<class 'dict'>


In [517]:
calculation.getMax()

[[6, 7, 8], [2, 5, 8], 8]

In [518]:
# dkm = str(2.449489742783178)
# print(dkm)

# components = list(dkm)
# print(components)

# counter = 0
# for c in components:
#     counter += 1

# print(counter)

def countLengthNumber(numb: float) -> int:
    components = list(str(numb))
    counter = 0
    
    for c in components:
        counter += 1
    
    return counter 

expectedLength = countLengthNumber(2.449489742783178)
currentLength = countLengthNumber(2.4494898)

print("Current length: {}\nExpected Length: {}".format(currentLength, expectedLength))

Current length: 9
Expected Length: 17


In [519]:
loz = "loz"
# print(len(loz))
l = list(loz)
print(l)

k = 2.44948974
print(round(k, 15))

['l', 'o', 'z']
2.44948974


## Testing

### Case 1

In [520]:
npArrTest1 = np.reshape(np.array([2,6,2,8,4,0,1,5,7]), (3, 3))

print(npArrTest1)

calcTest1 = MatrixStatisticalCalculation(npArrTest1)

print(calcTest1.getStatisticalInfor())


[[2 6 2]
 [8 4 0]
 [1 5 7]]
Std at cols: [3.091206165165235, 0.816496580927726, 2.943920288775949]
Std at rows: [1.8856180831641267, 3.265986323710904, 2.494438257849294]
Std at matrix: 2.6434171674156266
{'mean': [[3.6666666666666665, 5.0, 3.0], [3.3333333333333335, 4.0, 4.333333333333333], 3.888888888888889], 'variance': [[9.555555555555557, 0.6666666666666666, 8.666666666666666], [3.555555555555556, 10.666666666666666, 6.222222222222221], 6.987654320987654], 'standard deviation': [[3.091206165165235, 0.816496580927726, 2.943920288775949], [1.8856180831641267, 3.265986323710904, 2.494438257849294], 2.6434171674156266], 'max': [[8, 6, 7], [6, 8, 7], 8], 'min': [[1, 4, 0], [2, 0, 1], 0], 'sum': [[11, 15, 9], [10, 12, 13], 35]}


In [521]:
str1 = "{'mean': [[3.6666666666666665, 5.0, 3.0], [3.3333333333333335, 4.0, 4.333333333333333], 3.888888888888889], 'variance': [[9.555555555555557, 0.6666666666666666, 8.666666666666666], [3.555555555555556, 10.666666666666666, 6.222222222222221], 6.987654320987654], 'standard deviation': [[3.091206165165235, 0.816496580927726, 2.943920288775949], [1.8856180831641267, 3.265986323710904, 2.494438257849294], 2.6434171674156266], 'max': [[8, 6, 7], [6, 8, 7], 8], 'min': [[1, 4, 0], [2, 0, 1], 0], 'sum': [[11, 15, 9], [10, 12, 13], 35]}"
str2 = "{'mean': [[3.6666666666666665, 5.0, 3.0], [3.3333333333333335, 4.0, 4.333333333333333], 3.888888888888889], 'variance': [[9.555555555555557, 0.6666666666666666, 8.666666666666666], [3.555555555555556, 10.666666666666666, 6.222222222222221], 6.987654320987654], 'standard deviation': [[3.091206165165235, 0.816496580927726, 2.943920288775949], [1.8856180831641267, 3.265986323710904, 2.494438257849294], 2.6434171674156266], 'max': [array([8, 6, 7], array([6, 8, 7]), 8], 'min': [array([1, 4, 0]), array([2, 0, 1], dtype=int32), 0], 'sum': [array([11, 15,  9], dtype=int32), array([10, 12, 13], dtype=int32), 35]}"


In [522]:
sample = np.array([2,6,2,8,4,0,1,5,7])
print(sample.shape)

print(sample.shape == (9, ))

(9,)
True


### Case 2

In [528]:
npArrTest2 = np.array([2,6,2,8,4,0,1])

print(npArrTest2)

print(npArrTest2.shape)

[2 6 2 8 4 0 1]
(7,)


In [529]:
calcTest2 = MatrixStatisticalCalculation(npArrTest2)

ValueError: Input Numpy Array must contain 9 numbers!!!